server:
  port: 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    hikari:
      username: 
      password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
